name = "pulsekeep"
account_id = "15c5eb2bc79614f038cc2e6a9f9cffd4"
main = "src/worker.js"
compatibility_date = "2026-05-26"

assets = { directory = "web" }

[vars]
API_ORIGIN = "https://pulsekeep.fly.dev"

[placement]
mode = "smart"
